// ============================================================
//  components/appLang.ts
//
//  Забон — ЯК ҶОИ УМУМӢ, мисли нақл дар appTheme.ts.
//  Калид айни ҳамонест, ки Auth истифода мебарад (tajgram_lang),
//  барои ҳамин интихоби забон дар ҳамаи сайт якхела мемонад.
//
//  ҚОИДА: матни нав → ба ҲАР СЕ забон илова кунед.
//  Тоҷикӣ бо ҳарфҳои ТОҶИКӢ (кириллӣ), русӣ бо русӣ, англисӣ бо англисӣ.
// ============================================================

export type Lang = "tj" | "ru" | "en";

export const LANG_KEY = "tajgram_lang";
export const LANG_EVENT = "tajgram-lang";

export const LANGS: { code: Lang; short: string; label: string }[] = [
  { code: "tj", short: "TJ", label: "Тоҷикӣ" },
  { code: "ru", short: "RU", label: "Русский" },
  { code: "en", short: "EN", label: "English" },
];

export function readLang(): Lang {
  if (typeof localStorage === "undefined") return "tj";
  const saved = localStorage.getItem(LANG_KEY);
  return saved === "ru" || saved === "en" || saved === "tj" ? saved : "tj";
}

export function writeLang(lang: Lang) {
  if (typeof localStorage === "undefined") return;
  localStorage.setItem(LANG_KEY, lang);
  window.dispatchEvent(new CustomEvent<Lang>(LANG_EVENT, { detail: lang }));
}

export function onLangChange(listener: (lang: Lang) => void): () => void {
  if (typeof window === "undefined") return () => {};
  const handler = (event: Event) => {
    const detail = (event as CustomEvent<Lang>).detail;
    listener(detail === "ru" || detail === "en" ? detail : "tj");
  };
  window.addEventListener(LANG_EVENT, handler);
  return () => window.removeEventListener(LANG_EVENT, handler);
}

// ============================================================
//  Матнҳо. Намуна — англисӣ; tj ва ru ҳамон шаклро доранд.
// ============================================================
const en = {
  // ---- navigation ----
  navHome: "Home",
  navSearch: "Search",
  navExplore: "Explore",
  navReels: "Reels",
  navMessages: "Messages",
  navNotifications: "Notifications",
  navCreate: "Create",
  navProfile: "Profile",
  navMore: "More",
  navSettings: "Settings",
  navSaved: "Saved",
  navLanguage: "Language",
  themeDark: "Dark theme",
  themeLight: "Light theme",
  logout: "Log out",

  // ---- shared ----
  checking: "Checking...",
  loading: "Loading...",
  close: "Close",
  cancel: "Cancel",
  back: "Back",
  save: "Save",
  saving: "Saving...",
  delete: "Delete",
  previous: "Previous",
  next: "Next",
  search: "Search",
  clear: "Clear",
  loginFirst: "Sign in first",
  unknownError: "Unknown server error.",

  // ---- stories ----
  yourStory: "your story",
  noStories: "No new stories in the last 24 hours.",
  story: "Story",
  newStory: "New story",
  closeStory: "Close story",
  prevStory: "Previous story",
  nextStory: "Next story",
  scrollLeft: "Scroll stories left",
  scrollRight: "Scroll stories right",

  // ---- feed ----
  caughtUpTitle: "You are all caught up",
  caughtUpText: "You have seen all new posts from the past 3 days.",
  viewOlder: "View older posts",
  suggestedPosts: "Suggested Posts",
  noPostsTitle: "No posts yet",
  noPostsText: "Nothing has been published to this backend yet.",
  createPost: "Create post",

  // ---- comments ----
  addComment: "Add a comment...",
  send: "Post",
  sendAction: "Send",
  more: "more",
  viewAllComments: "View all comments",
  comments: "Comments",
  noComments: "No comments yet",
  commentsLoadFailed: "Could not load the comments.",
  commentFailed: "Could not post the comment.",
  emoji: "Emoji",
  likes: "likes",
  like: "like",
  likeAction: "Like",
  unlike: "Unlike",
  share: "Share",
  saveAction: "Save",
  unsave: "Remove from saved",
  moreOptions: "More options",

  // ---- suggestions ----
  suggestedForYou: "Suggested for you",
  seeAll: "See all",
  followsYou: "Follows you",
  friends: "You follow each other",
  noSuggestions: "No suggestions right now.",
  follow: "Follow",
  following: "Following",

  // ---- profile ----
  posts: "posts",
  followers: "followers",
  followingCount: "following",
  reels: "reels",
  editProfile: "Edit profile",
  noUserPosts: "No posts yet.",
  tabPosts: "Posts",
  tabReels: "Reels",
  tabSaved: "Saved",
  tabVideo: "Video",
  noReelsYet: "No reels yet",
  noVideosYet: "No videos yet",
  noSavedPosts: "Nothing saved yet",
  profileLoadFailed: "Could not load the profile",
  pageUnavailable: "Page unavailable",
  userNotFound: "User not found.",
  userNotPicked: "No user selected.",
  actionFailed: "Could not complete the action.",
  loadFailed: "Could not load.",

  // ---- explore / saved / notifications ----
  explore: "Explore",
  saved: "Saved",
  noSaved: "Nothing saved yet.",
  notifications: "Notifications",
  noActivity: "No activity yet.",
  notifAll: "All",
  notifFollows: "Follows",
  notifLikes: "Likes",
  notifMessages: "Messages",
  notifToday: "Today",
  notifThisWeek: "This week",
  notifEarlier: "Earlier",
  notifNew: "new",
  notifEmptyHint: "Likes, follows and messages will show up here.",
  notifTabEmpty: "Nothing in this tab yet.",
  settings: "Settings",

  // ---- new post ----
  createTitle: "Create post",
  pickFiles: "Choose a photo or video",
  picked: "Files chosen",
  captionTitle: "Title (optional)",
  captionText: "Description",
  publish: "Publish",
  publishing: "Publishing...",
  pickAtLeastOne: "Choose at least one file",
  publishFailed: "Could not publish",
  newPost: "New post",
  photosRequired: "Photos (required)",
  postTitlePlaceholder: "Post title",
  postTextPlaceholder: "About this post...",
  needOnePhoto: "At least one photo is required.",
  postFailed: "Could not publish the post.",
  removePhoto: "Remove photo",
  createSomething: "Create something new",
  typeUnsupported: "The server does not support this type yet.",
  pickFileFirst: "Choose a file first.",

  // ---- new reel ----
  newReel: "New reel",
  reelVideoRequired: "Video — required",
  reelCoverOptional: "Cover image — optional",
  reelTitleLabel: "Title",
  reelDescriptionLabel: "Description",
  reelTitlePlaceholder: "Reel title",
  reelTextPlaceholder: "About this video...",
  coverMustBeImage: "The cover must be an image.",
  pickVideoFirst: "Choose a video first — a reel cannot be made without one.",
  reelFailed: "Could not publish the reel.",
  removeVideo: "Remove video",
  views: "Views",

  // ---- edit profile ----
  aboutMe: "About me",
  aboutPlaceholder: "A few words about yourself...",
  gender: "Gender",
  genderMale: "Male",
  genderFemale: "Female",
  genderUnset: "Prefer not to say",
  photoUploadFailed: "Could not upload the photo.",
  photoRemoveFailed: "Could not remove the photo.",
  saveFailed: "Could not save.",
  storyFailed: "Could not publish the story. Try another photo.",

  // ---- settings ----
  settingsTitle: "Settings",
  secProfile: "Profile",
  secAppearance: "Appearance",
  secPrivacy: "Privacy",
  secNotifications: "Notifications",
  secPassword: "Change password",
  fieldUserName: "Username",
  fieldEmail: "Email",
  fieldFullName: "Full name",
  backendLocked: "The server does not allow changing this",
  theme: "Theme",
  themeDarkShort: "Dark",
  themeLightShort: "Light",
  language: "Language",
  oldPassword: "Current password",
  newPassword: "New password (at least 6 characters)",
  changePassword: "Change password",
  passwordTooShort: "The new password is shorter than 6 characters",
  passwordChanged: "Password changed",
  passwordChangeFailed: "Could not change the password",
  settingsSaved: "Saved",
  settingsSaveFailed: "Could not save",
  settingsLoadFailed: "Could not load the settings",
  photoChanged: "Photo updated",
  photoUploadError: "Could not upload the photo",
  photoRemoved: "Photo removed",
  photoRemoveError: "Could not remove the photo",
  profileSaved: "Profile saved",
  profileSaveFailed: "Could not save the profile",
  opened: "Opened",
  openFailed: "Could not open",
  changePhoto: "Change photo",
  newPhoto: "New photo",
  changeAction: "Change",
  blockedUsers: "Blocked users",
  nobodyBlocked: "Nobody is blocked.",
  unblock: "Unblock",
  blockAction: "Block",
  blockConfirmTitle: "Block this user?",
  blockConfirmText: "You will no longer see their posts, and they will not be able to write to you. They are not notified.",
  unblockConfirmTitle: "Unblock this user?",
  unblockConfirmText: "You will start seeing their posts again.",
  blockedBadge: "Blocked",
  blockedNotice: "You blocked this user",
  blockedNoticeHint: "Their posts are hidden from you. Only you see this — nobody else knows.",

  setPrivate: "Private account",
  setPrivateHint: "Only followers see your posts",
  setActivity: "Show activity status",
  setActivityHint: "Others can see when you are online",
  setComments: "Allow comments",
  setCommentsHint: "Others can comment on your posts",
  setMessages: "Allow messages",
  setMessagesHint: "Others can send you messages",
  setTags: "Allow tags",
  setTagsHint: "Others can tag you in posts",
  setNotifyLikes: "Likes",
  setNotifyComments: "Comments",
  setNotifyFollows: "New followers",
  setNotifyMessages: "Messages",
  setEmail: "Send to email",
  settingsUnavailable: "Settings unavailable",

  // ---- search ----
  searchTitle: "Search",
  searchPlaceholder: "Type a username...",
  searchHint: "Type someone's name — we will find them.",
  searchEmpty: "No such user found.",

  // ---- chats ----
  yourMessages: "Your messages",
  newChat: "New chat",
  noChatsYet: "No chats yet. Tap the button above to start one.",
  nothingFound: "Nothing found.",
  noMessagesYet: "No messages yet",
  messagePlaceholder: "Write a message...",
  messagesLoadFailed: "Could not load the messages.",
  messageSendFailed: "Could not send the message.",
  voiceSendFailed: "Could not send the voice message.",
  messageDeleteFailed: "Could not delete the message.",
  chatCreateFailed: "Could not create the chat.",
  notImageOrVideo: "is not an image or a video.",
  fileTooBig: "is too large (over 40 MB).",
  attachMedia: "Attach a photo or video",
  photoOrVideo: "Photo or video",
  addMorePhotos: "Add more photos",
  removeFile: "Remove the file",
  deleteMessage: "Delete the message",
  noFollowersYet: "Nobody follows you yet and you do not follow anybody yet.",
  usernamePlaceholder: "Username...",

  // ---- voice messages ----
  voiceMessage: "Voice message",
  recordVoice: "Record a voice message",
  sendVoice: "Send the recording",
  play: "Play",
  pause: "Pause",
  playbackSpeed: "Playback speed",
  recorderUnsupported: "This browser does not support voice recording.",
  micDenied: "Microphone access was denied.",
  micFailed: "Could not open the microphone.",

  // ---- calls ----
  call: "Call",
  audioCall: "Voice call",
  videoCall: "Video call",
  callNotAllowed: "Calls with this user are not available",
  serverLink: "Server connection",
  connecting: "Connecting...",
  noLink: "No connection",
  linkFailed: "Could not establish the connection.",
  decline: "Decline",
  accept: "Accept",
  micOn: "Turn the microphone on",
  micOff: "Turn the microphone off",
  camOn: "Turn the camera on",
  camOff: "Turn the camera off",
  endCall: "End the call",
  mediaFailed: "Could not open the microphone or camera.",
  peerNotFound: "Could not find the other person. Refresh the page.",
  userOffline: "The user is offline right now.",
  noAnswer: "No answer.",
  callFailed: "Could not start the call.",
  callRejected: "The call was declined.",
  callCancelled: "The call was cancelled.",
  callEnded: "The call ended.",

  // ---- reels ----
  filterAll: "All",
  filterFollowing: "Following",
  filterSaved: "Saved",
  noVideo: "No videos",
  sound: "Sound",

  // ---- errors / media ----
  profileUnavailable: "Profile unavailable: the server did not answer.",
  profileNotFound: "Profile not found",
  feedFailed: "Could not load the feed",
  mediaUnavailable: "Media unavailable",
  mute: "Mute",
  unmute: "Unmute",

  // ---- profil: matni kholi ----
  postsEmptyText: "Your photos and videos will appear here.",
  savedEmptyText: "Saved posts are visible only to YOU.",
  reelsEmptyText: "Your short videos will appear here.",
  noBio: "This user has not written anything about themselves yet",
  emptyList: "The list is empty.",
  titleFollowers: "Followers",
  titleFollowing: "Following",
  unfollow: "Unfollow",
  chat: "Chat",
  newReelBtn: "New reel",
  gearTitle: "Settings",

  // ---- vaqt ----
  today: "Today",
  yesterday: "Yesterday",

  // ---- shabaka ----
  offline: "No internet connection. Check your network.",
  retry: "Try again",
  signIn: "Sign in",

  // ---- suhbat / reels: matni kholi ----
  chatsGuestText: "Sign in to see your messages.",
  chatsEmptyText: "Pick a conversation or start a new one with a friend.",
  chatsIntro: "Only people who follow you, or whom you follow",
  reelsGuestText: "Sign in to watch reels.",
  reelsEmptyFollowing: "The people you follow have not posted any reels yet.",
  reelsEmptySaved: "You have not saved any reels yet.",
  reelsEmptyAll: "There are no reels on the server yet.",
  searchGuest: "Sign in to search.",

  // ---- zvanok ----

  // ---- khatohoi HTTP ----
  errTokenExpired: "Your session has expired. Please sign in again.",
  errForbidden: "You do not have permission.",
  errNotFound: "Not found",
  errTooLarge: "The file is too large. Choose a smaller one.",
  errServerAsleep: "The server is waking up. Please wait 30-60 seconds.",
  errServer: "Internal server error",
  errRequest: "Request failed",

  // ---- suhbat ----
  typing: "typing",
  noMessagesStart: "No messages yet. Write the first one.",
  cannotWrite:
    "You cannot write to this user: neither of you follows the other.",
  recordingTooShort: "The recording is too short — hold the button longer.",
  firstComment: "No comments yet. Be the first to write one.",

  // ---- menyui "soakhtan" ----
  fmtPost: "Post",
  fmtPostHint: "A photo or video for the feed",
  fmtReel: "Reel",
  fmtReelHint: "A short vertical video",
  fmtStory: "Story",
  fmtStoryHint: "Stays up for 24 hours",
  fmtHighlight: "Highlight",
  fmtHighlightHint: "Not available on the server yet",
  createThing: "Create",
  pickVideo: "Choose a video",
  pickPhoto: "Choose a photo",
  pickPhotoOrVideo: "Choose a photo or video",
  chosen: "Chosen",
  posting: "Posting...",
  post: "Post",

  // ---- tugmahoi profil ----
  message: "Message",
  unfollowShort: "Following",
  followShort: "Follow",
  firstPostHint: "Once you share your first post, it will appear here.",
  nobodyYet: "Nobody yet",
  notFoundShort: "Not found",
  listLoadFailed: "Could not load the list.",
  chatOpenFailed: "Could not open the chat.",
  signInToWrite: "Sign in to write a message.",
  openingChat: "Opening the chat...",
  sendFailed: "Could not send",
  beFirstComment: "Be the first to share what you think.",

  // ---- modalho ----
  photosStep: "01 / Photos (required)",
  titleStep: "02 / Title",
  textStep: "03 / Text",
  videoStep: "01 / Video — required",
  coverStep: "02 / Cover image — optional",
  reelTitleStep: "03 / Title",
  reelTextStep: "04 / Description",
  pickPhotos: "Choose photos",
  pickVideoCaps: "Choose a video",
  videoFormatsHint: "MP4 / MOV / WEBM ... — a photo alone is not enough",
  videoRequiredNote: "A video is required",
  uploading: "Uploading...",
  photoNew: "New photo",
  pleaseWait: "Please wait...",
  removeAction: "Remove",
  savingLong: "Saving...",
  saveShort: "Save",
  views2: "Views",
  photoAlt: "Photo",
  toFeed: "Go to feed",
  goToLogin: "Go to sign in",
  storyUploading: "Uploading the story...",
  storyUnavailable: "Story unavailable",
  callingOut: "Calling...",
  micCamUnsupported: "This browser does not support the microphone or camera.",
  micCamDenied: "Microphone or camera access was denied.",

  // ---------- Actualniy / Highlights (/Actual) ----------
  highlights: "Highlights",
  newHighlight: "New",
  highlightTitle: "Name",
  highlightTitlePlaceholder: "Trip, Friends, Food...",
  highlightCover: "Cover",
  highlightPickStories: "Pick stories",
  highlightNoStories: "You have no stories yet. Add a story first.",
  highlightPicked: "Picked",
  highlightCreate: "Create",
  highlightCreating: "Creating...",
  highlightSave: "Save",
  highlightDelete: "Delete highlight",
  highlightDeleteAsk: "Delete this highlight? The stories themselves stay.",
  highlightNeedTitle: "Enter a name",
  highlightNeedStory: "Pick at least one story",
  highlightFailed: "Could not save the highlight.",
  highlightLoadFailed: "Could not load highlights.",
  highlightRemoveStory: "REMOVE",
  highlightEmpty: "This highlight is empty.",

  // ---- Menyui chat (ChatMenu.tsx) ----
  chatSettings: "Chat settings",
  soundOn: "Sound on",
  soundOff: "Sound off",
  soundHint: "Play a sound for new messages",
  notifyOn: "Notifications on",
  notifyOff: "Notifications off",
  notifyHint: "Show a banner for new messages",
  blockUser: "Block user",
  blockAsk: "Block this user?",
  blockFailed: "Could not block the user.",
  deleteChat: "Delete chat",
  deleteChatAsk: "Delete this chat?",
  chatDeleteFailed: "Could not delete the chat.",
  confirmYes: "Yes",
};

export type Dict = typeof en;

const tj: Dict = {
  // ---- навигатсия ----
  navHome: "Асосӣ",
  navSearch: "Ҷустуҷӯ",
  navExplore: "Кашф",
  navReels: "Reels",
  navMessages: "Паёмҳо",
  navNotifications: "Огоҳиномаҳо",
  navCreate: "Гузоштан",
  navProfile: "Профил",
  navMore: "Боз ҳам",
  navSettings: "Танзимот",
  navSaved: "Захирашуда",
  navLanguage: "Забон",
  themeDark: "Мавзӯи торик",
  themeLight: "Мавзӯи равшан",
  logout: "Баромадан",

  // ---- умумӣ ----
  checking: "Санҷида истодааст...",
  loading: "Бор шуда истодааст...",
  close: "Пӯшидан",
  cancel: "Бекор кардан",
  back: "Бозгашт",
  save: "Нигоҳ доштан",
  saving: "Нигоҳ дошта истодаем...",
  delete: "Нест кардан",
  previous: "Пешина",
  next: "Навбатӣ",
  search: "Ҷустуҷӯ",
  clear: "Тоза кардан",
  loginFirst: "Аввал ба ҳисоб дароед",
  unknownError: "Хатои номаълум дар сервер.",

  // ---- ҳикояҳо ----
  yourStory: "ҳикояи шумо",
  noStories: "Дар 24 соати охир ҳикояи нав нест.",
  story: "Ҳикоя",
  newStory: "Ҳикояи нав",
  closeStory: "Ҳикояро пӯшед",
  prevStory: "Ҳикояи пешина",
  nextStory: "Ҳикояи навбатӣ",
  scrollLeft: "Ба чап",
  scrollRight: "Ба рост",

  // ---- лента ----
  caughtUpTitle: "Ҳамаашро дидед",
  caughtUpText: "Ҳамаи паёмҳои нави 3 рӯзи охирро дидед.",
  viewOlder: "Паёмҳои кӯҳна",
  suggestedPosts: "Паёмҳои тавсияшуда",
  noPostsTitle: "Ҳанӯз паём нест",
  noPostsText: "Дар ин сервер ҳанӯз чизе нашр нашудааст.",
  createPost: "Паём гузоштан",

  // ---- шарҳҳо ----
  addComment: "Шарҳ нависед...",
  send: "Фиристодан",
  sendAction: "Фиристодан",
  more: "боз",
  viewAllComments: "Ҳамаи шарҳҳо",
  comments: "Шарҳҳо",
  noComments: "Ҳанӯз шарҳ нест",
  commentsLoadFailed: "Шарҳҳо бор нашуданд.",
  commentFailed: "Шарҳ гузошта нашуд.",
  emoji: "Эмоҷӣ",
  likes: "писанд",
  like: "писанд",
  likeAction: "Писанд кардан",
  unlike: "Писандро гирифтан",
  share: "Мубодила",
  saveAction: "Захира кардан",
  unsave: "Аз захира гирифтан",
  moreOptions: "Имконоти дигар",

  // ---- тавсияҳо ----
  suggestedForYou: "Барои шумо тавсия",
  seeAll: "Ҳама",
  followsYou: "Ба шумо обуна аст",
  friends: "Ба ҳамдигар обуна",
  noSuggestions: "Ҳозир тавсия нест.",
  follow: "Обуна шудан",
  following: "Обуна шудед",

  // ---- профил ----
  posts: "паём",
  followers: "обуначӣ",
  followingCount: "обуна",
  reels: "reels",
  editProfile: "Таҳрири профил",
  noUserPosts: "Ҳанӯз паём нест.",
  tabPosts: "Паёмҳо",
  tabReels: "Reels",
  tabSaved: "Захирашуда",
  tabVideo: "Видео",
  noReelsYet: "Ҳанӯз reels нест",
  noVideosYet: "Ҳанӯз видео нест",
  noSavedPosts: "Ҳанӯз чизе захира накардаед",
  profileLoadFailed: "Профил бор нашуд",
  pageUnavailable: "Саҳифа дастрас нест",
  userNotFound: "Чунин корбар ёфт нашуд.",
  userNotPicked: "Корбар интихоб нашудааст.",
  actionFailed: "Амал иҷро нашуд.",
  loadFailed: "Бор нашуд.",

  // ---- кашф / захирашуда / огоҳиномаҳо ----
  explore: "Кашф",
  saved: "Захирашуда",
  noSaved: "Ҳанӯз чизе захира нашудааст.",
  notifications: "Огоҳиномаҳо",
  noActivity: "Ҳанӯз фаъолият нест.",
  notifAll: "Ҳама",
  notifFollows: "Обунаҳо",
  notifLikes: "Писандҳо",
  notifMessages: "Паёмҳо",
  notifToday: "Имрӯз",
  notifThisWeek: "Ҳафтаи ҷорӣ",
  notifEarlier: "Пештар",
  notifNew: "нав",
  notifEmptyHint: "Писандҳо, обунаҳо ва паёмҳо дар ин ҷо пайдо мешаванд.",
  notifTabEmpty: "Дар ин бахш ҳанӯз чизе нест.",
  settings: "Танзимот",

  // ---- паёми нав ----
  createTitle: "Паёми нав",
  pickFiles: "Акс ё видео интихоб кунед",
  picked: "Файл интихоб шуд",
  captionTitle: "Сарлавҳа (ихтиёрӣ)",
  captionText: "Тавсиф",
  publish: "Нашр кардан",
  publishing: "Нашр шуда истодааст...",
  pickAtLeastOne: "Ақаллан як файл интихоб кунед",
  publishFailed: "Нашр нашуд",
  newPost: "Паёми нав",
  photosRequired: "Суратҳо (ҳатмӣ)",
  postTitlePlaceholder: "Сарлавҳаи паём",
  postTextPlaceholder: "Дар бораи ин паём...",
  needOnePhoto: "Ақаллан ЯК сурат лозим аст.",
  postFailed: "Паём гузошта нашуд.",
  removePhoto: "Суратро нест кунед",
  createSomething: "Чизи нав сохтан",
  typeUnsupported: "Ин навъ дар сервер ҳанӯз нест.",
  pickFileFirst: "Аввал файлро интихоб кунед.",

  // ---- reel-и нав ----
  newReel: "Reel-и нав",
  reelVideoRequired: "Видео — ҳатмӣ",
  reelCoverOptional: "Сурати рӯи видео — ихтиёрӣ",
  reelTitleLabel: "Сарлавҳа",
  reelDescriptionLabel: "Тавсиф",
  reelTitlePlaceholder: "Сарлавҳаи reel",
  reelTextPlaceholder: "Дар бораи ин видео...",
  coverMustBeImage: "Сурати рӯи видео бояд СУРАТ бошад.",
  pickVideoFirst: "Аввал ВИДЕО интихоб кунед — бе он reel сохта намешавад.",
  reelFailed: "Reel гузошта нашуд.",
  removeVideo: "Видеоро нест кунед",
  views: "Дидашуда",

  // ---- таҳрири профил ----
  aboutMe: "Дар бораи ман",
  aboutPlaceholder: "Чанд калима дар бораи худ...",
  gender: "Ҷинс",
  genderMale: "Мард",
  genderFemale: "Зан",
  genderUnset: "Нагуфтан",
  photoUploadFailed: "Сурат гузошта нашуд.",
  photoRemoveFailed: "Сурат нест карда нашуд.",
  saveFailed: "Нигоҳ дошта нашуд.",
  storyFailed: "Ҳикоя гузошта нашуд. Сурати дигарро санҷед.",

  // ---- танзимот ----
  settingsTitle: "Танзимот",
  secProfile: "Профил",
  secAppearance: "Зоҳир",
  secPrivacy: "Махфият",
  secNotifications: "Огоҳиномаҳо",
  secPassword: "Иваз кардани парол",
  fieldUserName: "Номи корбар",
  fieldEmail: "Почтаи электронӣ",
  fieldFullName: "Номи пурра",
  backendLocked: "Сервер иваз карданашро намедиҳад",
  theme: "Мавзӯъ",
  themeDarkShort: "Торик",
  themeLightShort: "Равшан",
  language: "Забон",
  oldPassword: "Пароли кӯҳна",
  newPassword: "Пароли нав (ақаллан 6 белгӣ)",
  changePassword: "Паролро иваз кунед",
  passwordTooShort: "Пароли нав аз 6 белгӣ кам аст",
  passwordChanged: "Парол иваз шуд",
  passwordChangeFailed: "Парол иваз нашуд",
  settingsSaved: "Нигоҳ дошта шуд",
  settingsSaveFailed: "Нигоҳ дошта нашуд",
  settingsLoadFailed: "Танзимот бор нашуд",
  photoChanged: "Сурат иваз шуд",
  photoUploadError: "Сурат гузошта нашуд",
  photoRemoved: "Сурат нест карда шуд",
  photoRemoveError: "Сурат нест карда нашуд",
  profileSaved: "Профил нигоҳ дошта шуд",
  profileSaveFailed: "Профил нигоҳ дошта нашуд",
  opened: "Кушода шуд",
  openFailed: "Кушода нашуд",
  changePhoto: "Суратро иваз кунед",
  newPhoto: "Сурати нав",
  changeAction: "Иваз кардан",
  blockedUsers: "Корбарони блокшуда",
  nobodyBlocked: "Ҳеҷ кас блок нашудааст.",
  unblock: "Кушодан",
  blockAction: "Блок кардан",
  blockConfirmTitle: "Ин корбарро блок мекунед?",
  blockConfirmText: "Дигар постҳои ӯро намебинед ва ӯ ба шумо навишта наметавонад. Ба ӯ хабар дода намешавад.",
  unblockConfirmTitle: "Блокро мекушоед?",
  unblockConfirmText: "Постҳои ӯро дубора мебинед.",
  blockedBadge: "Блокшуда",
  blockedNotice: "Шумо ин корбарро блок кардаед",
  blockedNoticeHint: "Постҳои ӯ аз шумо пинҳонанд. Инро танҳо ШУМО мебинед — каси дигар намедонад.",

  setPrivate: "Ҳисоби пӯшида",
  setPrivateHint: "Танҳо обуначиён паёмҳои шуморо мебинанд",
  setActivity: "Ҳолати фаъолият",
  setActivityHint: "Дигарон мебинанд, ки шумо онлайн ҳастед",
  setComments: "Иҷозати шарҳҳо",
  setCommentsHint: "Дигарон ба паёмҳои шумо шарҳ навишта метавонанд",
  setMessages: "Иҷозати паёмҳо",
  setMessagesHint: "Дигарон ба шумо паём фиристода метавонанд",
  setTags: "Иҷозати белгизанӣ",
  setTagsHint: "Дигарон шуморо дар паёмҳо белгӣ карда метавонанд",
  setNotifyLikes: "Писандҳо",
  setNotifyComments: "Шарҳҳо",
  setNotifyFollows: "Обуначиёни нав",
  setNotifyMessages: "Паёмҳо",
  setEmail: "Ба почтаи электронӣ фиристодан",
  settingsUnavailable: "Танзимот дастрас нест",

  // ---- ҷустуҷӯ ----
  searchTitle: "Ҷустуҷӯ",
  searchPlaceholder: "Номи корбарро нависед...",
  searchHint: "Номи касеро нависед — мо ӯро меёбем.",
  searchEmpty: "Чунин корбар ёфт нашуд.",

  // ---- суҳбатҳо ----
  yourMessages: "Паёмҳои шумо",
  newChat: "Суҳбати нав",
  noChatsYet:
    "Ҳанӯз суҳбат нест. Тугмаи болоиро зада бо як одам суҳбат сар кунед.",
  nothingFound: "Чизе ёфт нашуд.",
  noMessagesYet: "Ҳанӯз паём нест",
  messagePlaceholder: "Паём нависед...",
  messagesLoadFailed: "Паёмҳо бор нашуданд.",
  messageSendFailed: "Паём фиристода нашуд.",
  voiceSendFailed: "Паёми овозӣ фиристода нашуд.",
  messageDeleteFailed: "Паём нест карда нашуд.",
  chatCreateFailed: "Суҳбат сохта нашуд.",
  notImageOrVideo: "сурат ё видео нест.",
  fileTooBig: "хеле калон аст (аз 40 МБ зиёд).",
  attachMedia: "Сурат ё видео гузоред",
  photoOrVideo: "Сурат ё видео",
  addMorePhotos: "Боз сурат гузоред",
  removeFile: "Файлро нест кунед",
  deleteMessage: "Паёмро нест кунед",
  noFollowersYet:
    "Ҳанӯз ҳеҷ кас ба шумо обуна нашудааст ва шумо ҳам ба касе обуна нашудаед.",
  usernamePlaceholder: "Номи корбар...",

  // ---- паёми овозӣ ----
  voiceMessage: "Паёми овозӣ",
  recordVoice: "Паёми овозӣ сабт кунед",
  sendVoice: "Овозро фиристед",
  play: "Гӯш кунед",
  pause: "Истонед",
  playbackSpeed: "Суръати навохтан",
  recorderUnsupported: "Ин браузер сабти овозро дастгирӣ намекунад.",
  micDenied: "Иҷозати микрофон дода нашуд.",
  micFailed: "Микрофон кушода нашуд.",

  // ---- занг ----
  call: "Занг",
  audioCall: "Занги садоӣ",
  videoCall: "Занги видеоӣ",
  callNotAllowed: "Бо ин корбар занг мумкин нест",
  serverLink: "Алоқа бо сервер",
  connecting: "Пайваст шуда истодааст...",
  noLink: "Алоқа нест",
  linkFailed: "Алоқа сохта нашуд.",
  decline: "Рад кардан",
  accept: "Қабул кардан",
  micOn: "Микрофонро даргиронед",
  micOff: "Микрофонро хомӯш кунед",
  camOn: "Камераро даргиронед",
  camOff: "Камераро хомӯш кунед",
  endCall: "Зангро тамом кунед",
  mediaFailed: "Микрофон ё камера кушода нашуд.",
  peerNotFound: "Нишонии ҳамсуҳбат ёфт нашуд. Саҳифаро нав кунед.",
  userOffline: "Корбар ҳозир дар шабака нест.",
  noAnswer: "Ҷавоб надоданд.",
  callFailed: "Занг нашуд.",
  callRejected: "Занг қабул нашуд.",
  callCancelled: "Занг бекор карда шуд.",
  callEnded: "Занг тамом шуд.",

  // ---- reels ----
  filterAll: "Ҳама",
  filterFollowing: "Обунаҳо",
  filterSaved: "Захирашуда",
  noVideo: "Видео нест",
  sound: "Садо",

  // ---- хатоҳо / медиа ----
  profileUnavailable: "Профил дастрас нест: сервер ҷавоб надод.",
  profileNotFound: "Профил ёфт нашуд",
  feedFailed: "Лентаро бор кардан нашуд",
  mediaUnavailable: "Файл дастрас нест",
  mute: "Садоро хомӯш кунед",
  unmute: "Садоро даргиронед",

  // ---- профил: матни холӣ ----
  postsEmptyText: "Суратҳо ва видеоҳои шумо дар ҳамин ҷо пайдо мешаванд.",
  savedEmptyText: "Паёмҳои захирашуда танҳо ба ШУМО намоён мешаванд.",
  reelsEmptyText: "Видеоҳои кӯтоҳи шумо дар ҳамин ҷо пайдо мешаванд.",
  noBio: "Ин корбар ҳанӯз дар бораи худ чизе нанавиштааст",
  emptyList: "Рӯйхат холӣ аст.",
  titleFollowers: "Обуначиён",
  titleFollowing: "Обунаҳо",
  unfollow: "Обунаро бекор кардан",
  chat: "Суҳбат",
  newReelBtn: "Reel-и нав",
  gearTitle: "Танзимот",

  // ---- вақт ----
  today: "Имрӯз",
  yesterday: "Дирӯз",

  // ---- шабака ----
  offline: "Интернет нест. Пайвастро санҷед.",
  retry: "Боз як бор санҷед",
  signIn: "Ба ҳисоб даромадан",

  // ---- суҳбат / reels: матни холӣ ----
  chatsGuestText: "Барои дидани паёмҳо бояд ба ҳисоб дароед.",
  chatsEmptyText: "Як суҳбатро интихоб кунед ё бо дӯстон суҳбати нав сар кунед.",
  chatsIntro: "Танҳо онҳое, ки ба шумо обуна шудаанд ё шумо ба онҳо",
  reelsGuestText: "Барои дидани reels бояд ба ҳисоб дароед.",
  reelsEmptyFollowing: "Онҳое, ки шумо обуна шудаед, ҳанӯз reels нагузоштаанд.",
  reelsEmptySaved: "Шумо ҳанӯз ҳеҷ reel-ро захира накардаед.",
  reelsEmptyAll: "Дар сервер ҳанӯз ҳеҷ reel нест.",
  searchGuest: "Барои ҷустуҷӯ аввал ба ҳисоб дароед.",

  // ---- занг ----

  // ---- хатоҳои HTTP ----
  errTokenExpired: "Мӯҳлати вуруд гузашт. Аз нав дароед.",
  errForbidden: "Иҷозат нест.",
  errNotFound: "Ёфт нашуд",
  errTooLarge: "Файл хеле калон аст. Хурдтарашро интихоб кунед.",
  errServerAsleep: "Сервер бедор шуда истодааст. 30-60 сония сабр кунед.",
  errServer: "Хатои дохилии сервер",
  errRequest: "Дархост иҷро нашуд",

  // ---- суҳбат ----
  typing: "менависад",
  noMessagesStart: "Ҳанӯз паём нест. Аввалин паёмро шумо нависед.",
  cannotWrite:
    "Бо ин корбар навиштан мумкин нест: на ӯ ба шумо обуна аст, на шумо ба ӯ.",
  recordingTooShort: "Овоз хеле кӯтоҳ аст — тугмаро дартар доред.",
  firstComment: "Ҳанӯз шарҳ нест. Аввалин шарҳ аз шумо бошад.",

  // ---- менюи "сохтан" ----
  fmtPost: "Паём",
  fmtPostHint: "Сурат ё видео ба лента",
  fmtReel: "Reel",
  fmtReelHint: "Видеои кӯтоҳи амудӣ",
  fmtStory: "Ҳикоя",
  fmtStoryHint: "24 соат мемонад",
  fmtHighlight: "Ҳамешагӣ",
  fmtHighlightHint: "Дар сервер ҳанӯз нест",
  createThing: "Чизи нав",
  pickVideo: "Видео интихоб кунед",
  pickPhoto: "Сурат интихоб кунед",
  pickPhotoOrVideo: "Сурат ё видео интихоб кунед",
  chosen: "Интихоб шуд",
  posting: "Гузошта истодааст...",
  post: "Гузоштан",

  // ---- тугмаҳои профил ----
  message: "Паём",
  unfollowShort: "Обуна шудед",
  followShort: "Обуна",
  firstPostHint: "Вақте паёми аввалро гузоред, он дар ҳамин ҷо пайдо мешавад.",
  nobodyYet: "Ҳанӯз кас нест",
  notFoundShort: "Ёфт нашуд",
  listLoadFailed: "Рӯйхат бор нашуд.",
  chatOpenFailed: "Суҳбат кушода нашуд.",
  signInToWrite: "Барои навиштан бояд ба ҳисоб дароед.",
  openingChat: "Суҳбат кушода истодааст...",
  sendFailed: "Фиристода нашуд",
  beFirstComment: "Аввалин шуда фикратонро нависед.",

  // ---- модалҳо ----
  photosStep: "01 / СУРАТҲО (ҲАТМӢ)",
  titleStep: "02 / САРЛАВҲА",
  textStep: "03 / МАТН",
  videoStep: "01 / ВИДЕО — ҲАТМӢ",
  coverStep: "02 / СУРАТИ РӮИ ВИДЕО — ИХТИЁРӢ",
  reelTitleStep: "03 / САРЛАВҲА",
  reelTextStep: "04 / ТАВСИФ",
  pickPhotos: "СУРАТ ИНТИХОБ КУНЕД",
  pickVideoCaps: "ВИДЕО ИНТИХОБ КУНЕД",
  videoFormatsHint: "MP4 / MOV / WEBM ... — ФАҚАТ СУРАТ КИФОЯ НЕСТ",
  videoRequiredNote: "ВИДЕО ЛОЗИМ АСТ",
  uploading: "БОР КАРДА ИСТОДААСТ...",
  photoNew: "Сурати нав",
  pleaseWait: "Сабр кунед...",
  removeAction: "Нест кардан",
  savingLong: "Нигоҳ дошта истодааст...",
  saveShort: "Нигоҳ дор",
  views2: "ДИДАШУДА",
  photoAlt: "Сурат",
  toFeed: "Ба лента",
  goToLogin: "Ба саҳифаи вуруд",
  storyUploading: "Ҳикоя бор карда истодааст...",
  storyUnavailable: "Ҳикоя дастрас нест",
  callingOut: "Занг меравад...",
  micCamUnsupported: "Ин браузер микрофон ё камераро дастгирӣ намекунад.",
  micCamDenied: "Иҷозати микрофон ё камера дода нашуд.",

  // ---------- Actualniy / Highlights (/Actual) ----------
  highlights: "Актуалӣ",
  newHighlight: "Нав",
  highlightTitle: "Ном",
  highlightTitlePlaceholder: "Сафар, Дӯстон, Хӯрок...",
  highlightCover: "Муқова",
  highlightPickStories: "Story-ҳоро интихоб кунед",
  highlightNoStories: "Ҳанӯз story надоред. Аввал story гузоред.",
  highlightPicked: "Интихоб шуд",
  highlightCreate: "Сохтан",
  highlightCreating: "Сохта истодааст...",
  highlightSave: "Нигоҳ дор",
  highlightDelete: "Актуалиро тарк кардан",
  highlightDeleteAsk: "Ин актуалӣ тарк карда шавад? Худи story-ҳо мемонанд.",
  highlightNeedTitle: "Ном нависед",
  highlightNeedStory: "Ақаллан як story интихоб кунед",
  highlightFailed: "Актуалӣ нигоҳ дошта нашуд.",
  highlightLoadFailed: "Актуалиҳо бор нашуданд.",
  highlightRemoveStory: "БАРОВАРДАН",
  highlightEmpty: "Ин актуалӣ холӣ аст.",

  // ---- Menyui chat (ChatMenu.tsx) ----
  chatSettings: "Танзимоти чат",
  soundOn: "Садо фаъол",
  soundOff: "Садо хомӯш",
  soundHint: "Барои паёмҳои нав садо дода шавад",
  notifyOn: "Огоҳиномаҳо фаъол",
  notifyOff: "Огоҳиномаҳо хомӯш",
  notifyHint: "Барои паёми нав огоҳинома нишон дода шавад",
  blockUser: "Баста кардан",
  blockAsk: "Ин корбарро баста кунем?",
  blockFailed: "Баста кардан нашуд.",
  deleteChat: "Чатро нест кардан",
  deleteChatAsk: "Ин чатро нест кунем?",
  chatDeleteFailed: "Чат нест нашуд.",
  confirmYes: "Ҳа",
};

const ru: Dict = {
  // ---- навигация ----
  navHome: "Главная",
  navSearch: "Поиск",
  navExplore: "Интересное",
  navReels: "Reels",
  navMessages: "Сообщения",
  navNotifications: "Уведомления",
  navCreate: "Создать",
  navProfile: "Профиль",
  navMore: "Ещё",
  navSettings: "Настройки",
  navSaved: "Сохранённое",
  navLanguage: "Язык",
  themeDark: "Тёмная тема",
  themeLight: "Светлая тема",
  logout: "Выйти",

  // ---- общее ----
  checking: "Проверяем...",
  loading: "Загрузка...",
  close: "Закрыть",
  cancel: "Отмена",
  back: "Назад",
  save: "Сохранить",
  saving: "Сохраняем...",
  delete: "Удалить",
  previous: "Предыдущее",
  next: "Следующее",
  search: "Поиск",
  clear: "Очистить",
  loginFirst: "Сначала войдите",
  unknownError: "Неизвестная ошибка сервера.",

  // ---- истории ----
  yourStory: "ваша история",
  noStories: "За последние 24 часа новых историй нет.",
  story: "История",
  newStory: "Новая история",
  closeStory: "Закрыть историю",
  prevStory: "Предыдущая история",
  nextStory: "Следующая история",
  scrollLeft: "Прокрутить влево",
  scrollRight: "Прокрутить вправо",

  // ---- лента ----
  caughtUpTitle: "Вы всё посмотрели",
  caughtUpText: "Вы видели все новые публикации за 3 дня.",
  viewOlder: "Показать старые",
  suggestedPosts: "Рекомендации",
  noPostsTitle: "Публикаций пока нет",
  noPostsText: "На этом сервере ещё ничего не опубликовано.",
  createPost: "Создать пост",

  // ---- комментарии ----
  addComment: "Добавьте комментарий...",
  send: "Отправить",
  sendAction: "Отправить",
  more: "ещё",
  viewAllComments: "Все комментарии",
  comments: "Комментарии",
  noComments: "Комментариев пока нет",
  commentsLoadFailed: "Не удалось загрузить комментарии.",
  commentFailed: "Не удалось отправить комментарий.",
  emoji: "Эмодзи",
  likes: "отметок «Нравится»",
  like: "отметка «Нравится»",
  likeAction: "Нравится",
  unlike: "Убрать «Нравится»",
  share: "Поделиться",
  saveAction: "Сохранить",
  unsave: "Убрать из сохранённого",
  moreOptions: "Ещё",

  // ---- рекомендации ----
  suggestedForYou: "Рекомендации для вас",
  seeAll: "Все",
  followsYou: "Подписан на вас",
  friends: "Вы подписаны друг на друга",
  noSuggestions: "Сейчас рекомендаций нет.",
  follow: "Подписаться",
  following: "Вы подписаны",

  // ---- профиль ----
  posts: "публикаций",
  followers: "подписчиков",
  followingCount: "подписок",
  reels: "reels",
  editProfile: "Редактировать профиль",
  noUserPosts: "Публикаций пока нет.",
  tabPosts: "Публикации",
  tabReels: "Reels",
  tabSaved: "Сохранённое",
  tabVideo: "Видео",
  noReelsYet: "Reels пока нет",
  noVideosYet: "Видео пока нет",
  noSavedPosts: "Пока ничего не сохранено",
  profileLoadFailed: "Не удалось загрузить профиль",
  pageUnavailable: "Страница недоступна",
  userNotFound: "Такой пользователь не найден.",
  userNotPicked: "Пользователь не выбран.",
  actionFailed: "Не удалось выполнить действие.",
  loadFailed: "Не удалось загрузить.",

  // ---- интересное / сохранённое / уведомления ----
  explore: "Интересное",
  saved: "Сохранённое",
  noSaved: "Пока ничего не сохранено.",
  notifications: "Уведомления",
  noActivity: "Активности пока нет.",
  notifAll: "Все",
  notifFollows: "Подписки",
  notifLikes: "Лайки",
  notifMessages: "Сообщения",
  notifToday: "Сегодня",
  notifThisWeek: "На этой неделе",
  notifEarlier: "Ранее",
  notifNew: "новых",
  notifEmptyHint: "Лайки, подписки и сообщения появятся здесь.",
  notifTabEmpty: "В этой вкладке пока пусто.",
  settings: "Настройки",

  // ---- новая публикация ----
  createTitle: "Новая публикация",
  pickFiles: "Выберите фото или видео",
  picked: "Файлов выбрано",
  captionTitle: "Заголовок (необязательно)",
  captionText: "Описание",
  publish: "Опубликовать",
  publishing: "Публикуем...",
  pickAtLeastOne: "Выберите хотя бы один файл",
  publishFailed: "Не удалось опубликовать",
  newPost: "Новая публикация",
  photosRequired: "Фотографии (обязательно)",
  postTitlePlaceholder: "Заголовок публикации",
  postTextPlaceholder: "Об этой публикации...",
  needOnePhoto: "Нужна хотя бы одна фотография.",
  postFailed: "Не удалось опубликовать.",
  removePhoto: "Удалить фото",
  createSomething: "Создать новое",
  typeUnsupported: "Сервер пока не поддерживает этот тип.",
  pickFileFirst: "Сначала выберите файл.",

  // ---- новый reel ----
  newReel: "Новый reel",
  reelVideoRequired: "Видео — обязательно",
  reelCoverOptional: "Обложка — необязательно",
  reelTitleLabel: "Заголовок",
  reelDescriptionLabel: "Описание",
  reelTitlePlaceholder: "Заголовок reel",
  reelTextPlaceholder: "Об этом видео...",
  coverMustBeImage: "Обложка должна быть изображением.",
  pickVideoFirst: "Сначала выберите ВИДЕО — без него reel не создать.",
  reelFailed: "Не удалось опубликовать reel.",
  removeVideo: "Удалить видео",
  views: "Просмотры",

  // ---- редактирование профиля ----
  aboutMe: "О себе",
  aboutPlaceholder: "Несколько слов о себе...",
  gender: "Пол",
  genderMale: "Мужской",
  genderFemale: "Женский",
  genderUnset: "Не указывать",
  photoUploadFailed: "Не удалось загрузить фото.",
  photoRemoveFailed: "Не удалось удалить фото.",
  saveFailed: "Не удалось сохранить.",
  storyFailed: "Не удалось опубликовать историю. Попробуйте другое фото.",

  // ---- настройки ----
  settingsTitle: "Настройки",
  secProfile: "Профиль",
  secAppearance: "Внешний вид",
  secPrivacy: "Конфиденциальность",
  secNotifications: "Уведомления",
  secPassword: "Смена пароля",
  fieldUserName: "Имя пользователя",
  fieldEmail: "Эл. почта",
  fieldFullName: "Полное имя",
  backendLocked: "Сервер не разрешает это менять",
  theme: "Тема",
  themeDarkShort: "Тёмная",
  themeLightShort: "Светлая",
  language: "Язык",
  oldPassword: "Текущий пароль",
  newPassword: "Новый пароль (минимум 6 символов)",
  changePassword: "Сменить пароль",
  passwordTooShort: "Новый пароль короче 6 символов",
  passwordChanged: "Пароль изменён",
  passwordChangeFailed: "Не удалось сменить пароль",
  settingsSaved: "Сохранено",
  settingsSaveFailed: "Не удалось сохранить",
  settingsLoadFailed: "Не удалось загрузить настройки",
  photoChanged: "Фото обновлено",
  photoUploadError: "Не удалось загрузить фото",
  photoRemoved: "Фото удалено",
  photoRemoveError: "Не удалось удалить фото",
  profileSaved: "Профиль сохранён",
  profileSaveFailed: "Не удалось сохранить профиль",
  opened: "Открыто",
  openFailed: "Не удалось открыть",
  changePhoto: "Изменить фото",
  newPhoto: "Новое фото",
  changeAction: "Изменить",
  blockedUsers: "Заблокированные",
  nobodyBlocked: "Никто не заблокирован.",
  unblock: "Разблокировать",
  blockAction: "Заблокировать",
  blockConfirmTitle: "Заблокировать пользователя?",
  blockConfirmText: "Вы больше не увидите его публикации, и он не сможет вам писать. Ему об этом не сообщат.",
  unblockConfirmTitle: "Разблокировать пользователя?",
  unblockConfirmText: "Вы снова будете видеть его публикации.",
  blockedBadge: "Заблокирован",
  blockedNotice: "Вы заблокировали этого пользователя",
  blockedNoticeHint: "Его публикации скрыты от вас. Это видите только ВЫ — больше никто.",

  setPrivate: "Закрытый аккаунт",
  setPrivateHint: "Публикации видят только подписчики",
  setActivity: "Статус активности",
  setActivityHint: "Другие видят, что вы в сети",
  setComments: "Разрешить комментарии",
  setCommentsHint: "Другие могут комментировать ваши публикации",
  setMessages: "Разрешить сообщения",
  setMessagesHint: "Другие могут писать вам сообщения",
  setTags: "Разрешить отметки",
  setTagsHint: "Другие могут отмечать вас в публикациях",
  setNotifyLikes: "Отметки «Нравится»",
  setNotifyComments: "Комментарии",
  setNotifyFollows: "Новые подписчики",
  setNotifyMessages: "Сообщения",
  setEmail: "Отправлять на эл. почту",
  settingsUnavailable: "Настройки недоступны",

  // ---- поиск ----
  searchTitle: "Поиск",
  searchPlaceholder: "Введите имя пользователя...",
  searchHint: "Введите чьё-нибудь имя — мы его найдём.",
  searchEmpty: "Такой пользователь не найден.",

  // ---- чаты ----
  yourMessages: "Ваши сообщения",
  newChat: "Новый чат",
  noChatsYet: "Чатов пока нет. Нажмите кнопку выше, чтобы начать общение.",
  nothingFound: "Ничего не найдено.",
  noMessagesYet: "Сообщений пока нет",
  messagePlaceholder: "Напишите сообщение...",
  messagesLoadFailed: "Не удалось загрузить сообщения.",
  messageSendFailed: "Не удалось отправить сообщение.",
  voiceSendFailed: "Не удалось отправить голосовое сообщение.",
  messageDeleteFailed: "Не удалось удалить сообщение.",
  chatCreateFailed: "Не удалось создать чат.",
  notImageOrVideo: "не является фото или видео.",
  fileTooBig: "слишком большой (больше 40 МБ).",
  attachMedia: "Прикрепить фото или видео",
  photoOrVideo: "Фото или видео",
  addMorePhotos: "Добавить ещё фото",
  removeFile: "Удалить файл",
  deleteMessage: "Удалить сообщение",
  noFollowersYet:
    "На вас пока никто не подписан, и вы ни на кого не подписаны.",
  usernamePlaceholder: "Имя пользователя...",

  // ---- голосовые ----
  voiceMessage: "Голосовое сообщение",
  recordVoice: "Записать голосовое сообщение",
  sendVoice: "Отправить запись",
  play: "Воспроизвести",
  pause: "Пауза",
  playbackSpeed: "Скорость воспроизведения",
  recorderUnsupported: "Этот браузер не поддерживает запись голоса.",
  micDenied: "Доступ к микрофону не разрешён.",
  micFailed: "Не удалось открыть микрофон.",

  // ---- звонки ----
  call: "Звонок",
  audioCall: "Аудиозвонок",
  videoCall: "Видеозвонок",
  callNotAllowed: "Звонки с этим пользователем недоступны",
  serverLink: "Связь с сервером",
  connecting: "Подключаемся...",
  noLink: "Нет связи",
  linkFailed: "Не удалось установить соединение.",
  decline: "Отклонить",
  accept: "Принять",
  micOn: "Включить микрофон",
  micOff: "Выключить микрофон",
  camOn: "Включить камеру",
  camOff: "Выключить камеру",
  endCall: "Завершить звонок",
  mediaFailed: "Не удалось открыть микрофон или камеру.",
  peerNotFound: "Не удалось найти собеседника. Обновите страницу.",
  userOffline: "Пользователь сейчас не в сети.",
  noAnswer: "Не ответили.",
  callFailed: "Не удалось позвонить.",
  callRejected: "Звонок отклонён.",
  callCancelled: "Звонок отменён.",
  callEnded: "Звонок завершён.",

  // ---- reels ----
  filterAll: "Все",
  filterFollowing: "Подписки",
  filterSaved: "Сохранённое",
  noVideo: "Видео нет",
  sound: "Звук",

  // ---- ошибки / медиа ----
  profileUnavailable: "Профиль недоступен: сервер не ответил.",
  profileNotFound: "Профиль не найден",
  feedFailed: "Не удалось загрузить ленту",
  mediaUnavailable: "Файл недоступен",
  mute: "Выключить звук",
  unmute: "Включить звук",

  // ---- профиль: пустые состояния ----
  postsEmptyText: "Ваши фото и видео появятся здесь.",
  savedEmptyText: "Сохранённые публикации видны только ВАМ.",
  reelsEmptyText: "Ваши короткие видео появятся здесь.",
  noBio: "Этот пользователь пока ничего о себе не написал",
  emptyList: "Список пуст.",
  titleFollowers: "Подписчики",
  titleFollowing: "Подписки",
  unfollow: "Отписаться",
  chat: "Чат",
  newReelBtn: "Новый reel",
  gearTitle: "Настройки",

  // ---- время ----
  today: "Сегодня",
  yesterday: "Вчера",

  // ---- сеть ----
  offline: "Нет интернета. Проверьте соединение.",
  retry: "Попробовать снова",
  signIn: "Войти",

  // ---- чаты / reels: пустые состояния ----
  chatsGuestText: "Войдите, чтобы увидеть свои сообщения.",
  chatsEmptyText: "Выберите чат или начните новый разговор с друзьями.",
  chatsIntro: "Только те, кто подписан на вас или на кого подписаны вы",
  reelsGuestText: "Войдите, чтобы смотреть reels.",
  reelsEmptyFollowing: "Те, на кого вы подписаны, ещё не публиковали reels.",
  reelsEmptySaved: "Вы пока не сохранили ни одного reel.",
  reelsEmptyAll: "На сервере пока нет ни одного reel.",
  searchGuest: "Войдите, чтобы искать.",

  // ---- звонки ----

  // ---- ошибки HTTP ----
  errTokenExpired: "Сессия истекла. Войдите заново.",
  errForbidden: "Нет доступа.",
  errNotFound: "Не найдено",
  errTooLarge: "Файл слишком большой. Выберите поменьше.",
  errServerAsleep: "Сервер просыпается. Подождите 30-60 секунд.",
  errServer: "Внутренняя ошибка сервера",
  errRequest: "Запрос не выполнен",

  // ---- чат ----
  typing: "печатает",
  noMessagesStart: "Сообщений пока нет. Напишите первое.",
  cannotWrite:
    "Вы не можете писать этому пользователю: вы не подписаны друг на друга.",
  recordingTooShort: "Запись слишком короткая — держите кнопку дольше.",
  firstComment: "Комментариев пока нет. Напишите первый.",

  // ---- меню "создать" ----
  fmtPost: "Публикация",
  fmtPostHint: "Фото или видео в ленту",
  fmtReel: "Reel",
  fmtReelHint: "Короткое вертикальное видео",
  fmtStory: "История",
  fmtStoryHint: "Хранится 24 часа",
  fmtHighlight: "Актуальное",
  fmtHighlightHint: "На сервере пока нет",
  createThing: "Создать",
  pickVideo: "Выберите видео",
  pickPhoto: "Выберите фото",
  pickPhotoOrVideo: "Выберите фото или видео",
  chosen: "Выбрано",
  posting: "Публикуем...",
  post: "Опубликовать",

  // ---- кнопки профиля ----
  message: "Сообщение",
  unfollowShort: "Вы подписаны",
  followShort: "Подписаться",
  firstPostHint: "Когда вы опубликуете первый пост, он появится здесь.",
  nobodyYet: "Пока никого нет",
  notFoundShort: "Не найдено",
  listLoadFailed: "Не удалось загрузить список.",
  chatOpenFailed: "Не удалось открыть чат.",
  signInToWrite: "Войдите, чтобы написать сообщение.",
  openingChat: "Открываем чат...",
  sendFailed: "Не отправлено",
  beFirstComment: "Будьте первым, кто оставит комментарий.",

  // ---- модальные окна ----
  photosStep: "01 / ФОТО (ОБЯЗАТЕЛЬНО)",
  titleStep: "02 / ЗАГОЛОВОК",
  textStep: "03 / ТЕКСТ",
  videoStep: "01 / ВИДЕО — ОБЯЗАТЕЛЬНО",
  coverStep: "02 / ОБЛОЖКА — НЕОБЯЗАТЕЛЬНО",
  reelTitleStep: "03 / ЗАГОЛОВОК",
  reelTextStep: "04 / ОПИСАНИЕ",
  pickPhotos: "ВЫБЕРИТЕ ФОТО",
  pickVideoCaps: "ВЫБЕРИТЕ ВИДЕО",
  videoFormatsHint: "MP4 / MOV / WEBM ... — ОДНОГО ФОТО НЕДОСТАТОЧНО",
  videoRequiredNote: "НУЖНО ВИДЕО",
  uploading: "ЗАГРУЖАЕМ...",
  photoNew: "Новое фото",
  pleaseWait: "Подождите...",
  removeAction: "Удалить",
  savingLong: "Сохраняем...",
  saveShort: "Сохранить",
  views2: "ПРОСМОТРЫ",
  photoAlt: "Фото",
  toFeed: "В ленту",
  goToLogin: "На страницу входа",
  storyUploading: "Загружаем историю...",
  storyUnavailable: "История недоступна",
  callingOut: "Звоним...",
  micCamUnsupported: "Этот браузер не поддерживает микрофон или камеру.",
  micCamDenied: "Доступ к микрофону или камере не разрешён.",

  // ---------- Actualniy / Highlights (/Actual) ----------
  highlights: "Актуальное",
  newHighlight: "Новое",
  highlightTitle: "Название",
  highlightTitlePlaceholder: "Поездка, Друзья, Еда...",
  highlightCover: "Обложка",
  highlightPickStories: "Выберите истории",
  highlightNoStories: "У вас пока нет историй. Сначала добавьте историю.",
  highlightPicked: "Выбрано",
  highlightCreate: "Создать",
  highlightCreating: "Создаём...",
  highlightSave: "Сохранить",
  highlightDelete: "Удалить актуальное",
  highlightDeleteAsk: "Удалить это актуальное? Сами истории останутся.",
  highlightNeedTitle: "Введите название",
  highlightNeedStory: "Выберите хотя бы одну историю",
  highlightFailed: "Не удалось сохранить актуальное.",
  highlightLoadFailed: "Не удалось загрузить актуальное.",
  highlightRemoveStory: "УБРАТЬ",
  highlightEmpty: "Это актуальное пустое.",

  // ---- Menyui chat (ChatMenu.tsx) ----
  chatSettings: "Настройки чата",
  soundOn: "Звук включён",
  soundOff: "Звук выключен",
  soundHint: "Звук для новых сообщений",
  notifyOn: "Уведомления включены",
  notifyOff: "Уведомления выключены",
  notifyHint: "Показывать баннер о новых сообщениях",
  blockUser: "Заблокировать",
  blockAsk: "Заблокировать пользователя?",
  blockFailed: "Не удалось заблокировать пользователя.",
  deleteChat: "Удалить чат",
  deleteChatAsk: "Удалить этот чат?",
  chatDeleteFailed: "Не удалось удалить чат.",
  confirmYes: "Да",
};

export const dictionary: Record<Lang, Dict> = { tj, ru, en };

/**
 * Lughat BERUNI React.
 *
 * Ba'ze joyho (api.ts, WebRTC) hook navishta nametavonand, vale
 * matni onho ham ba korbar namoyon meshavad. In jo zaboni joriro
 * az localStorage megirem - hamon kalide ki <LocaleProvider> dorad.
 */
export function tr(): Dict {
  return dictionary[readLang()];
}

